# Until upstream fpm bug is fixed, build the apk pkg directly:
# https://github.com/jordansissel/fpm/issues/1227
FROM alpine:3.6
MAINTAINER Claudio Ramirez <pub.claudio@gmail.com>

ENV LANG C.UTF-8
ENV TZ Europe/Brussels
ENV packages bash build-base git musl-dev perl wget

RUN set -xv ; \
apk update && apk upgrade && \
# Packages for compiling and pkg creation
apk add --no-cache ${packages} ${packages_tmp} && \
update-ca-certificates && \
cp /usr/share/zoneinfo/${TZ} /etc/localtime && \
echo "${TZ}" > /etc/timezone && \
# Cleanup
rm -rf /tmp/* /var/tmp/*

COPY pkg_rakudo /
COPY install_zef_as_user /
COPY install_zef_as_root /

CMD '/pkg_rakudo'
