FROM alpine:3.5
MAINTAINER Claudio Ramirez <pub.claudio@gmail.com>

ENV LANG C.UTF-8
ENV TZ Europe/Brussels
ENV packages tzdata gcc git make perl ruby-dev lsb-release
ENV packages_tmp tzdata wget

RUN set -xv ; \
cp /usr/share/zoneinfo/${TZ} /etc/localtime && \
echo "${TZ}" > /etc/timezone && \
apk update && apk upgrade && \
# Packages for compiling and pkg creation
apk add --no-cache ${packages} ${packages_tmp} && \
gem install fpm && \
# Cleanup
apk del ${packages_tmp} && \
rm -rf /tmp/* /var/tmp/* /MoarVM* /nqp* /rakudo*

COPY pkg_rakudo /
COPY install_zef_as_user /
COPY install_zef_as_root /

CMD '/pkg_rakudo'
